"""add note chunks table
Revision ID: a3c1e2f4b5d6
Revises: '9ac199d8d97a'
Create Date: 2026-08-24 11:30:00.000000
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a3c1e2f4b5d6'
down_revision: Union[str, None] = '9ac199d8d97a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'note_chunks',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('note_id', sa.UUID(), nullable=False),
        sa.Column('profile_id', sa.UUID(), nullable=False),
        sa.Column('chunk_index', sa.Integer(), nullable=False),
        sa.Column('chunk_text', sa.Text(), nullable=False),
        sa.Column('token_count', sa.Integer(), nullable=False),
        sa.Column('overlap_tokens', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('start_character', sa.Integer(), nullable=True),
        sa.Column('end_character', sa.Integer(), nullable=True),
        sa.Column('previous_chunk_id', sa.UUID(), nullable=True),
        sa.Column('next_chunk_id', sa.UUID(), nullable=True),
        sa.Column('version', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('embedding_status', sa.String(length=50), nullable=False, server_default='pending'),
        sa.ForeignKeyConstraint(['next_chunk_id'], ['note_chunks.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['previous_chunk_id'], ['note_chunks.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_chunks_note_id'), 'note_chunks', ['note_id'], unique=False)
    op.create_index(op.f('ix_note_chunks_profile_id'), 'note_chunks', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_chunks_profile_id'), table_name='note_chunks')
    op.drop_index(op.f('ix_note_chunks_note_id'), table_name='note_chunks')
    op.drop_table('note_chunks')
    # ### end Alembic commands ###